### ISSUE TITLE
EXPDAT-001 create an App that starts and shows title

### ISSUE THREAD

**Issue by zwerg4** [sw21-tug/Team_25#1]
MERGE with #9 
MERGE with #9 
MERGE with #9 
MERGE with #9 

EXPDAT-001

**As a** user

**I want** an app that starts

**and that** shows "EXPIRY DATE"

# feature criteria
- [ ] white screen diplays  "EXPIRY DATE" in it
- [ ] no warnings and erros in debug

# technical
- [ ] Android SDK: Android 8 API level 26
- [ ] Testing framework: junit test for now - https://developer.android.com/reference/junit/framework/TestSuite

# Acceptance criteria
- [ ] runs local without errors
- [ ] commit message contains issue abbreviations
- [ ] commits are squased
- [ ] tests written for it

**Comment by bbruenner** [comment]
added technical criteria

**Comment by bbruenner** [comment]
tutorial for junit: https://developer.android.com/training/testing/unit-testing/local-unit-tests
