### ISSUE TITLE
EXPDAT-021 russian language support

### ISSUE THREAD

**Issue by zwerg4** [sw21-tug/Team_25#21]
# user story

**As a** user

**I want** to be able to change the language

**so that** I can choose between english and russian and all the texts in the app changes to that

# feature criteria
- [ ] add a dropdown menu at the top right of the title where you can choose between english and russian
- [ ] if the language changes all app view has to be reloaded to the new language

# Acceptance criteria
- [ ] runs local without errors
- [ ] commit message contains issue abbreviations
- [ ] tests written for it

**Comment by bbruenner** [comment]
https://developer.android.com/reference/androidx/preference/package-summary
https://developer.android.com/reference/android/content/SharedPreferences
