### ISSUE TITLE
EXPDAT-12/001 api

### ISSUE THREAD

**Issue by bbruenner** [sw21-tug/Team_25#39]
# substory of #12 

# technical stuff
- [ ] api request
- [ ] have a async function to map could call.
- [ ] return ARRAY of Lat/Lng coordinates as TUBLES
- [ ] https://foodsharing.de/api/map/markers?types[]=fairteiler&types[]=baskets

# Acceptance criteria
- [ ] runs local without errors
- [ ] commit message contains issue abbreviations
- [ ] tests written for it

**Comment by steschi** [comment]
API now not async as map will call api in coroutine, lat / lon stored in a format that the map can use (not as tuples though)
