### ISSUE TITLE
EXPDAT-053 keyboard closes after save 

### ISSUE THREAD

**Issue by zwerg4** [sw21-tug/Team_25#53]
# user story

**As a** user

**I want** that the keyboard closes automatically

**so that** when I save a new product I the keyboard is going away 

# technical stuff
- [ ] keyboard closes after "save date"

# Acceptance criteria
- [ ] runs local without errors
- [ ] commit message contains issue abbreviations
- [ ] commits are squased
- [ ] tests written for it

**Comment by bbruenner** [comment]
https://dev.to/collinskesuibai/show-hide-android-soft-keyboard-android-31-seconds-of-code-1297
