### ISSUE TITLE
EXPDAT-006 edit or delete saved products

### ISSUE THREAD

**Issue by zwerg4** [sw21-tug/Team_25#6]
# user story

# split into #22 and #24 
# split into #22 and #24 

**As a** user

**I want** to see the detail view for a product with a delete and edit button

**so that** i can delete or edit an item.

linked with detail view 8

# feature
- [ ] delete button: click on it to delete it immediately without a confirm button and closes the popover
- [ ] edit button: click on it to turn label to editable field. name and expiry date
- [ ] edit button changes to save. click on save will update db
- [ ] back button is visible in edit view as cancel option. 

# technical
- [ ] db remove
- [ ] db update 

# Acceptance criteria
- [ ] runs local without errors
- [ ] commit message contains issue abbreviations
- [ ] commits are squased
- [ ] tests written for it

**Comment by bbruenner** [comment]
closing, split into #22 #24
