### ISSUE TITLE
EXPDAT-007 get suggestion for this product

### ISSUE THREAD

**Issue by zwerg4** [sw21-tug/Team_25#7]
# user story
**As a** user

**I want** to get some suggestions/ideas on how to us this product (ex. recipe)

**so that** i can cook something with it

# feature criteria
 - [ ] display a small list of recipes if available
 - [ ] recipes in list should be a clickable on name and image ( if available), which opens url from recipe
 - [ ] list  is shown in single product overview #8
 - [ ] "loading" in the start
 - [ ] if no products found, remove "loading" placeholder text
 - [ ] display only one.

# Mockup
![list_Mockup](https://user-images.githubusercontent.com/29690863/119669855-ad4eca00-be38-11eb-86e2-179553b952fb.png)

# Acceptance criteria
- [ ] runs local without errors
- [ ] commit message contains issue abbreviations
- [ ] commits are squased
- [ ] tests written for it

# helpful links
https://rapidapi.com/spoonacular/api/recipe-food-nutrition
https://spoonacular.com/food-api/docs

**Comment by benjowun** [comment]
Getting recipes: https://rapidapi.com/de/spoonacular/api/recipe-food-nutrition/
- includes code snippet for how to do the request in kotlin
- Look for "Search Recipes by Ingrediants endpoint"
- response contains image link where available
- api requirs a signup, but it seemed to me to be useable for free, at least the demo code worked fine on my end

**Comment by benjowun** [comment]
Image loading:
- picasso library seemed simplest in my tests: (http://www.codeplayon.com/2019/11/how-to-load-image-from-url-android-example/)
- pure kotlin alternative: https://www.tutorialspoint.com/how-do-i-load-an-imageview-by-url-on-android-using-kotlin

**Comment by benjowun** [comment]
Open Recipe URL on click:
- https://stackoverflow.com/questions/4930228/open-a-url-on-click-of-ok-button-in-android
